version: '2'

# volumes:


services:
  nginx_reverse_proxy:
    image: nginx
    # container_name: prometheus
    ports:
      - "5000:5000"

    volumes:
      - /home/glitch/Documents/tech_ref/nginx_related/boilerplates/:/etc/nginx/conf.d/
      
  
    
    depends_on:
      - zero_fox_layer
      
  zero_fox_layer:
    image: zero_fox_layer_flask_napalm:0.17
    
    