version: '3'


volumes:
  nginx_proxy_mgr-data:

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "tim_glitch"
      DB_MYSQL_PASSWORD: "tim_glitch"
      DB_MYSQL_NAME: "tim_glitch"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'tim_glitch'
      MYSQL_DATABASE: 'tim_glitch'
      MYSQL_USER: 'tim_glitch'
      MYSQL_PASSWORD: 'tim_glitch'
    volumes:
      - nginx_proxy_mgr-data:/var/lib/mysql